### ISSUE TITLE
Newbie  Questions

### ISSUE THREAD

**Issue by SelfReflection31** [JACOBSMILE/tmodloader1.4#23]
Hello I just downloaded this and ran it with Unraid. having some hiccups 

Is there a reason why config file is deprecated?
will TMOD_UPNP/ upnp option every be looked at or added? eager to use it for a friend group of mine. I have no idea how to make the server joinable for them with this.

**Comment by JACOBSMILE** [comment]
Hi @SelfReflection31 ,

The config file is deprecated mainly because there's an environment variable available for every setting. UPNP is untested because it requires specific network conditions to support it. Within a Docker container on UNRAID,  I don't know if it will work.

I'd recommend looking into Port Forwarding to enable remote connections to your server.
