### ISSUE TITLE
new World

### ISSUE THREAD

**Issue by ySteini** [JACOBSMILE/tmodloader1.4#40]
Hi, I have a problem with my current terraria World, my Terraria Server in docker wasnt working so I updated the Docker-App and now my world is gone. Is there any possible way to load an old world from a file?

**Comment by Poshy163** [comment]
If you have already shut down the docker container, without specifying any host storage location, unfortunately not

**Comment by JACOBSMILE** [comment]
Hi @ySteini , did you ever map a local host directory for it to store and persist World Files? If you did, then it should be as simple as copying the world into the new directory structure (new directory named /data) and specifying the name in the container environment variable.

If you did not have it storing worlds in a host mapper directory, then unfortunately the world has been deleted because containers are ephemeral without persistent storage.

I'd recommend reviewing the README about the section on the data directory and how to persist worlds and mod data.

**Comment by ySteini** [comment]
thank you, that worked, also is there a possible way to give myself owner on the server?
